---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/consents":
    post:
      summary: send consent form
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                email:
                  type: string
                country:
                  type: string
              required:
              - language
              - email
              - country
  "/api/v1/participants":
    get:
      summary: list participants
      security:
      - bearer: []
      responses:
        '200':
          description: successful
    post:
      summary: create participant
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phone_number:
                  type: string
                code:
                  type: string
                referrer_code:
                  type: string
                sgm_group:
                  type: string
                referrer_sgm_group:
                  type: string
                match:
                  type: string
                preferred_contact_method:
                  type: string
                name:
                  type: string
                country:
                  type: string
                seed:
                  type: boolean
                seed_id:
                  type: string
              required:
              - code
  "/api/v1/participants/verify":
    post:
      summary: verify participant
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verification_code:
                  type: string
                id:
                  type: integer
              required:
              - verification_code
              - id
  "/api/v1/participants/check":
    post:
      summary: check participant by code
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
              - code
  "/api/v1/participants/check_seed":
    post:
      summary: check participant by seed id
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                seed_id:
                  type: string
              required:
              - seed_id
  "/api/v1/participants/amend":
    put:
      summary: update participant attributes
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phone_number:
                  type: string
                code:
                  type: string
                referrer_code:
                  type: string
                sgm_group:
                  type: string
                referrer_sgm_group:
                  type: string
                match:
                  type: string
                preferred_contact_method:
                  type: string
                name:
                  type: string
                country:
                  type: string
                seed:
                  type: boolean
                seed_id:
                  type: string
              required:
              - email
  "/api/v1/participants/update_and_resend":
    put:
      summary: update participant attributes
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                contact:
                  type: string
                language:
                  type: string
              required:
              - id
              - contact
              - language
  "/api/v1/participants/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show participant
      security:
      - bearer: []
      responses:
        '200':
          description: successful
    put:
      summary: update participant
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phone_number:
                  type: string
                name:
                  type: string
                code:
                  type: string
                referrer_code:
                  type: string
                sgm_group:
                  type: string
                referrer_sgm_group:
                  type: string
                match:
                  type: string
                preferred_contact_method:
                  type: string
                seed:
                  type: boolean
                seed_id:
                  type: string
                country:
                  type: string
              required:
              - id
    delete:
      summary: delete participant
      security:
      - bearer: []
      responses:
        '200':
          description: successful
  "/api/v1/survey_responses":
    post:
      summary: create survey_response
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                survey_uuid:
                  type: string
                response_uuid:
                  type: string
                survey_complete:
                  type: boolean
                survey_title:
                  type: string
                eligible:
                  type: boolean
                consented:
                  type: boolean
                participant_id:
                  type: integer
                country:
                  type: string
  "/api/v1/survey_responses/safety":
    post:
      summary: send safety planning form
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                responses:
                  type: string
              required:
              - responses
  "/api/v1/survey_responses/amend":
    put:
      summary: update survey_response attributes
      security:
      - bearer: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                survey_uuid:
                  type: string
                response_uuid:
                  type: string
                survey_complete:
                  type: boolean
                survey_title:
                  type: string
                country:
                  type: string
                eligible:
                  type: boolean
                consented:
                  type: boolean
                source:
                  type: string
                language:
                  type: string
              required:
              - response_uuid
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
    bearer:
      type: http
      scheme: bearer
